import './style.css'

const icon = name => {
  const paths = {arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',spark:'<path d="m12 3 1.6 4.4L18 9l-4.4 1.6L12 15l-1.6-4.4L6 9l4.4-1.6L12 3Z"/>',chart:'<path d="M4 19V9m6 10V5m6 14v-7m4 7H2"/>',message:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="m15 9 6-6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'}
  return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]}</svg>`
}
const checks = items => `<ul class="check-list">${items.map(x=>`<li>${icon('check')}<span>${x}</span></li>`).join('')}</ul>`
const problems=['Postezi, dar prea puține postări ajung la conversații reale.','Vorbești cu oamenii și îi ajuți, dar eviți să faci oferta.','Îți este greu să spui prețul fără să justifici sau să reduci.','La „mă mai gândesc”, nu știi dacă să revii sau simți că deranjezi.','Depinzi de recomandări și perioade bune, fără să știi ce poți repeta.','Îmbunătățești produsul sau profilul, dar amâni contactul cu piața.','Spui „oamenii nu cumpără”, dar nu ai cifre care arată unde se rupe traseul.','Operaționalul îți ocupă ziua, iar vânzarea rămâne pentru „când ai timp”.']
const steps=[['Vizibilitate relevantă','Nu doar „să postezi”, ci să ajungi în fața oamenilor potriviți cu mesaje în care se pot recunoaște.'],['Conversație','Deschizi dialogul, pui întrebări și înțelegi problema, contextul, dorința și urgența reală.'],['Ofertă','Explici simplu ce rezolvi, pentru cine, cum lucrezi, ce primește clientul, cât durează și cât costă.'],['Follow-up','Revii cu respect, clarifici ce a rămas neînțeles și nu lași conversația neterminată.'],['Decizie','Îl ajuți să privească lucid problema, soluția, resursele și potrivirea — pentru un da sau un nu asumat.']]
const weeks=[['Claritate înainte de acțiune',['Alegi oferta pentru septembrie','Clarifici cui se adresează','Stabilești obiectivul și cifrele','Desenezi traseul actual','Identifici categoria evitată']],['Vizibilitate și conversații',['Construiești mesaje relevante','Folosești relații și comunități','Inițiezi conversații','Întrebi înainte de soluție','Colectezi limbajul pieței']],['Ofertă, valoare și preț',['Legi problema de soluție','Prezinți rezultatul și procesul','Spui prețul clar','Inviți omul să cumpere','Observi ce lipsește deciziei']],['Follow-up și optimizare',['Revii la leadurile în așteptare','Separi obiecția reală','Ceri decizia fără presiune','Analizezi ce a produs mișcare','Construiești planul următor']]]
const faqs=[['Nu am o audiență mare. Are sens pentru mine?','Da, dacă ai acces la oameni prin relații, comunități, grupuri, recomandări, parteneriate sau conversații directe. Vizibilitatea relevantă nu înseamnă neapărat mii de urmăritori.'],['Programul este doar pentru servicii?','Nu. Principiile se aplică serviciilor, produselor, afacerilor locale și businessurilor din domenii diverse.'],['Dacă încă îmi clarific oferta?','Poți intra dacă ai o competență, un produs sau o ofertă pe care o poți alege pentru luna septembrie. Dacă pornești complet de la zero, poate fi prea devreme.'],['Cât timp îmi ia zilnic?','Aproximativ 20–40 de minute pentru misiunea și acțiunea comercială.'],['Trebuie să particip live?','Participarea live este recomandată. Dacă nu poți, vei avea acces la înregistrări în perioada comunicată. Calendarul complet este trimis înainte de start.'],['Dacă nu termin toate cele 100 de acțiuni?','Nu ești eliminat. Trackerul te ajută să vezi ce ai făcut și ce ai evitat. Scopul este progresul măsurabil.'],['Primesc scripturi?','Da, modele pentru conversații, ofertă și follow-up, pe care le adaptezi contextului tău.'],['Care este diferența dintre Basic și VIP?','Basic oferă procesul complet. VIP adaugă audit, feedback direct, clinici suplimentare și hot seats. VIP este limitat la 12 locuri.'],['Îmi garantezi că voi vinde?','Nu. Rezultatul depinde de ofertă, piață, preț, volum și implementare. Primești cadrul și feedbackul pentru a identifica ce trebuie ajustat.'],['Pot plăti în rate?','Pentru această ofertă, plata este integrală.'],['Primesc factură?','Da. Completezi datele necesare după plată, iar factura este emisă conform fluxului comunicat.'],['Ce se întâmplă după plată?','Primești confirmarea, completezi formularul de înscriere și apoi primești accesul, calendarul și onboardingul.'],['Care este politica de retragere?','Drepturile tale sunt cele prevăzute de legislația aplicabilă contractelor la distanță. Consultă Termenii și condițiile înainte de plată.']]

document.querySelector('#app').innerHTML=`
<div class="page"><div class="scroll-progress"><span></span></div>
<header class="site-header"><a class="logo" href="#top"><b>B↗</b><span>BACK TO <strong>SALES</strong></span></a><nav><a href="#proces">Procesul</a><a href="#program">Programul</a><a href="#pachete">Pachete</a></nav><a class="button small" href="#pachete">Vreau să intru ${icon('arrow')}</a></header>
<main id="top">
<section class="hero shell"><div class="hero-copy reveal"><div class="kicker">— Challenge practic de vânzări • 1–30 septembrie</div><h1>Ajută-ți clientul să <em>cumpere</em> de la tine.</h1><p class="lead">În 30 de zile îți clarifici traseul comercial și faci <strong>100 de acțiuni concrete</strong> prin care clientul potrivit te poate vedea, poate intra în conversație, poate înțelege oferta și poate lua o decizie.</p><p class="no-pressure">Fără mesaje trimise în masă. Fără presiune.<br>Fără promisiuni de venit care nu depind numai de tine.</p><div class="hero-actions"><a class="button gold" href="#pachete">Vreau să intru în Back to Sales ${icon('arrow')}</a><span><b>Early-bird până pe 23 august</b><br>Basic 179 lei • VIP 437 lei</span></div><small class="secure">◈ Plată securizată · Preț final, fără TVA adăugat</small></div>
<div class="hero-visual reveal"><i class="orbit"></i><i class="sphere"></i><div class="dashboard"><div class="dash-top"><span>PROGRES COMERCIAL</span><span>● LIVE</span></div><strong>100</strong><p>acțiuni măsurabile</p><div class="bars">${'<i></i>'.repeat(7)}</div><div class="stats"><span><b>30</b>zile</span><span><b>5</b>etape</span><span><b>1</b>proces</span></div></div><div class="float one">${icon('target')}<span><b>Claritate</b> înainte de acțiune</span></div><div class="float two">${icon('message')}<span><b>Conversații</b> care avansează</span></div></div></section>
<div class="trust">${[["clock","30 de zile","de acțiune ghidată"],["chart","100 de acțiuni","comerciale urmărite"],["message","Scripturi și exemple","adaptabile"],["users","Feedback","și comunitate"]].map(x=>`<div>${icon(x[0])}<span><b>${x[1]}</b>${x[2]}</span></div>`).join('')}</div>

<section class="section soft"><div class="shell intro reveal"><small>01 / REALITATEA</small><h2>Muncești mult în business. Dar câte acțiuni pot duce la o <em>vânzare?</em></h2><p>Poate ai un produs bun, experiență și clienți mulțumiți. Și totuși, vânzările sunt inegale. Într-o lună apar recomandări. În alta, scad încasările și îți dai seama că nu ai un proces pe care să te bazezi.</p></div><div class="shell problem-grid reveal">${problems.map((x,i)=>`<article><b>0${i+1}</b><p>${x}</p></article>`).join('')}</div><div class="shell insight reveal"><b>Problema nu este că nu muncești suficient.</b><p>De multe ori muncești enorm, dar acțiunile comerciale sunt prea rare, neclare sau se opresc înainte de ofertă și decizie.</p><a href="#pachete">Vreau un ritm clar ${icon('arrow')}</a></div></section>

<section class="section dark"><div class="shell two-col reveal"><div><small>02 / SCHIMBAREA DE PERSPECTIVĂ</small><h2>Vânzarea nu începe când spui <em>prețul.</em></h2></div><div><p>Clientul nu cumpără doar pentru că produsul tău este bun. Mai întâi trebuie să afle că exiști. Să se recunoască în problemă. Să intre într-o conversație. Să înțeleagă soluția, prețul și implementarea. Apoi să poată lua o decizie.</p><p>Dacă nu ai vizibilitate, ai nevoie de distribuție. Dacă oamenii nu se recunosc în mesaj, ai nevoie de limbajul lor. Dacă pornești conversații, dar nu faci oferta, încă o postare nu rezolvă evitarea. Dacă există interes și nu revii, pierzi leaduri deja câștigate.</p></div></div><div class="shell principle reveal">${icon('spark')}<p>Nu ai nevoie să împingi oamenii să cumpere. Ai nevoie să construiești traseul prin care clientul potrivit își identifică nevoia, înțelege dacă oferta îl ajută și poate alege informat.</p></div></section>

<section class="section" id="proces"><div class="shell reveal"><small>03 / MECANISMUL BACK TO SALES</small><div class="title-row"><h2>Cele 5 categorii care construiesc <em>vânzarea.</em></h2><p>100 de acțiuni distribuite inteligent — ca să vezi ce produce interes, conversații, oferte și decizii.</p></div><div class="steps">${steps.map((x,i)=>`<article><b>0${i+1}</b><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>

<section class="section soft"><div class="shell volume reveal"><div class="hundred"><strong>100</strong><span>ACȚIUNI<br>NU PRESUPUNERI</span></div><div><small>04 / DE CE VOLUM?</small><h2>Șase încercări nu sunt suficiente ca să spui <em>„nu funcționează”.</em></h2><p>Cu volum și măsurare apar tipare: ce mesaj deschide conversația, ce client răspunde, unde oamenii se opresc, ce obiecție se repetă și ce canal aduce leaduri potrivite.</p><blockquote>Nu poți controla cine cumpără. Dar poți controla câte ocazii reale creezi și cât de bine înveți din răspunsul pieței.</blockquote></div></div></section>

<section class="section"><div class="shell reveal"><small>05 / REZULTATUL</small><div class="title-row"><h2>La final ai un <em>proces testat de tine.</em></h2><p>Un sistem comercial mai clar, construit pe acțiuni și pe date din piața ta.</p></div><div class="outcomes">${checks(['O singură ofertă prioritară pentru septembrie.','O formulare mai clară a clientului și rezultatului.','Harta traseului de la primul contact la decizie.','Tracker cu 100 de acțiuni și răspunsuri.','Mai multe conversații pornite intenționat.','Un mod simplu de a prezenta oferta și prețul.'])}${checks(['Scripturi adaptabile, nu replici robotice.','Un sistem de follow-up fără presiune.','Lista obiecțiilor reale din piața ta.','Date care arată ce trebuie ajustat.','Un plan comercial pentru următoarele 30 de zile.'])}</div><div class="honesty"><b>O promisiune onestă</b><p>Nu promit un anumit număr de clienți sau o sumă de venit. Rezultatul depinde de ofertă, preț, piață și implementare. Programul îți oferă cadrul, acțiunile, feedbackul și datele necesare.</p></div></div></section>

<section class="section dark" id="program"><div class="shell reveal"><small>06 / CELE 30 DE ZILE</small><div class="title-row"><h2>Patru săptămâni. Un traseu comercial <em>complet.</em></h2><p>De la claritate la conversație, de la ofertă la decizie și optimizare.</p></div><div class="weeks">${weeks.map((x,i)=>`<article><div><b>0${i+1}</b><small>SĂPTĂMÂNA ${i+1}</small></div><h3>${x[0]}</h3>${checks(x[1])}</article>`).join('')}</div><div class="delivery">${[["clock","20–40 min / zi","Misiuni clare"],["chart","Tracker inclus","Acțiune și răspuns"],["users","Întâlniri săptămânale","Implementare"],["message","Grup + resurse","Scripturi și fișe"]].map(x=>`<div>${icon(x[0])}<span><b>${x[1]}</b><small>${x[2]}</small></span></div>`).join('')}</div></div></section>

<section class="section pricing" id="pachete"><div class="shell reveal"><small>07 / ALEGE VARIANTA</small><div class="title-row"><h2>Proces complet sau proces + <em>feedback personalizat.</em></h2><p>Basic nu este incomplet. VIP înseamnă mai multă personalizare și acces direct.</p></div><div class="price-grid">
<article class="price-card"><div class="plan"><b>BASIC</b><small>PENTRU STRUCTURĂ ȘI RITM</small></div><p>Pentru tine dacă ai nevoie de structură, misiuni și un ritm care să te scoată din amânare.</p>${checks(['Programul complet de 30 de zile','Misiuni zilnice + trackerul celor 100 de acțiuni','Warm-up înainte de start','4 întâlniri + sesiunea finală','Scripturi, exemple și fișa traseului','Grup comun și feedback colectiv','Materiale și înregistrări 60 de zile'])}<div class="price-block"><small class="offer-label">EARLY-BIRD</small><div><strong class="price-value">179</strong> LEI</div><p class="price-note">până pe 23 august, 23:59 · apoi 237 lei</p></div><a class="button payment" data-plan="basic" data-standard="https://buy.stripe.com/aFaaEX7lT0sZ4bq8go5J60a" href="https://buy.stripe.com/eVqeVdeOl6Rn9vK8go5J608">Aleg Basic — <span class="button-price">179</span> lei ${icon('arrow')}</a><small>Preț final · Nu se adaugă TVA</small></article>
<article class="price-card featured"><i>MAXIMUM 12 LOCURI</i><div class="plan"><b>VIP</b><small>PENTRU FEEDBACK DIRECT</small></div><p>Pentru tine dacă ai o ofertă mai complexă sau vrei feedback direct pe situația ta.</p>${checks(['Tot ce este inclus în Basic','Auditul ofertei și traseului clientului','Clinici VIP săptămânale + hot seats','Feedback pe pitch și comunicarea prețului','Feedback pe mesaje și follow-up','Analiza cifrelor și blocajelor','Grup VIP restrâns + prioritate'])}<div class="price-block"><small class="offer-label">EARLY-BIRD</small><div><strong class="price-value">437</strong> LEI</div><p class="price-note">până pe 23 august, 23:59 · apoi 537 lei</p></div><a class="button gold payment" data-plan="vip" data-standard="https://buy.stripe.com/dRmeVdeOlcbH23i9ks5J60b" href="https://buy.stripe.com/28EbJ1ay58ZvfU82W45J609">Aleg VIP — <span class="button-price">437</span> lei ${icon('arrow')}</a><small>Preț final · Nu se adaugă TVA</small></article></div><div class="choice" id="contact"><div><b>Nu știi ce să alegi?</b><p>Spune-mi ce vinzi și unde te blochezi. Îți recomand sincer varianta potrivită, nu cea mai scumpă.</p></div><a class="button outline contact" href="https://wa.me/40746266529?text=Bun%C4%83%2C%20Claudia!%20Vreau%20o%20recomandare%20pentru%20pachetul%20Back%20to%20Sales.">Scrie-mi pe WhatsApp ${icon('arrow')}</a></div></div></section>

<section class="section soft"><div class="shell fit reveal"><article><small>ESTE PENTRU TINE DACĂ</small><h2>Ai ceva valoros de pus în piață.</h2>${checks(['Ești freelancer, prestator, coach, terapeut, consultant sau trainer.','Ești creator, producător sau ai un business local.','Lucrezi în turism, educație, sănătate, construcții, retail sau servicii.','Ai experiență, dar nu ai un proces comercial repetabil.','Nu ai audiență mare, dar poți intra în conversații.'])}</article><article class="not-fit"><small>NU ESTE PENTRU TINE DACĂ</small><h2>Cauți o scurtătură fără acțiune.</h2>${checks(['Vrei o formulă prin care oamenii spun da indiferent de ofertă.','Vrei doar să citești, fără să faci acțiunile.','Aștepți venit sau clienți garantați.','Nu ai nicio idee ce vrei să vinzi.','Nu poți aloca 20–40 de minute pe zi.'])}</article></div></section>

<section class="section"><div class="shell about reveal"><div class="portrait"><img src="/claudia-cioceanu.jpeg" alt="Claudia Cioceanu, Business & Performance Coach" width="1008" height="1012"><span><b>CLAUDIA CIOCEANU</b><small>Business & Performance Coach</small></span><i>12 ani<small>experiență</small></i></div><div><small>08 / DESPRE CLAUDIA</small><h2>Nu te învăț o tehnică pe care am citit-o <em>ieri.</em></h2><p class="lead">Lucrez la intersecția dintre business, vânzări și comportamentul omului.</p><p>Sunt Claudia Cioceanu, Business & Performance Coach. Am 12 ani de experiență în corporație, în vânzări și coordonarea echipelor, și o bază de economist cu pregătire în management.</p><p>Lucrez cu antreprenori pe claritatea ofertei, poziționare, preț, acțiune, performanță și blocajele care îi fac să se țină mici.</p><p>Metoda mea pornește de la diagnostic: îl ajuți pe om să-și identifice nevoia, înțelegi contextul, prezinți soluția relevantă și îi lași libertatea unei decizii informate.</p><div class="credentials"><span>12 ani corporație</span><span>Vânzări + coordonare</span><span>Business & Performance Coach</span></div></div></div></section>

<section class="section stories"><div class="shell reveal"><small>09 / SITUAȚII REALE</small><div class="title-row"><h2>Problema nu este mereu cea spusă <em>prima dată.</em></h2><p>Cazuri anonimizate care arată unde se poate rupe procesul comercial.</p></div><div class="story-grid">${[['„Am nevoie de mai multe încasări.”','Antreprenorul era copleșit de operațional, nu făcuse oferte noi și nu revenise la cei interesați. Îi lipsea un loc clar pentru vânzare în fiecare zi.'],['„Nu știu dacă va funcționa.”','Fusese dezamăgit de soluții generale. Avea nevoie de un proces adaptat contextului, nu de încă un „fă marketing”.'],['„Oamenii nu cumpără.”','Leadurile existau, dar nu erau urmărite. Oferta varia, cifrele lipseau, iar conversațiile nu aveau pas următor.'],['„Nu vreau să deranjez.”','Oferă multă valoare, dar evită oferta. A vinde etic înseamnă claritate fără să forțezi.']].map(x=>`<article><i>“</i><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>

<section class="section promise"><div class="shell two-col reveal"><div><small>10 / CE NU PROMIT</small><h2>Fără magie.<br>Fără manipulare.<br><em>Cu proces.</em></h2></div><div>${checks(['Nu îți promit că fiecare acțiune produce o vânzare.','Nu îți promit o sumă sau un număr de clienți.','Nu îți promit că un script înlocuiește o ofertă slabă.','Nu te învăț să inventezi urgență sau să împingi oamenii.'])}<p class="promise-end">Îți ofer un proces în care <b>faci, măsori, înțelegi și ajustezi.</b></p></div></div></section>

<section class="section"><div class="shell faq reveal"><small>11 / ÎNTREBĂRI FRECVENTE</small><h2>Poate te întrebi...</h2>${faqs.map((x,i)=>`<details ${i===0?'open':''}><summary>${x[0]}<i></i></summary><p>${x[1]}</p></details>`).join('')}</div></section>

<section class="final"><div class="shell reveal"><small>ÎNSCRIERILE SE ÎNCHID PE 30 AUGUST · 23:59</small><h2>În septembrie poți spera că vânzările apar.<br><em>Sau poți construi acțiunile care le fac posibile.</em></h2><p>Nu trebuie să devii mai agresiv sau să postezi fără oprire. Ai nevoie să alegi acțiunile care pot produce un răspuns și să afli ce funcționează.</p><div><a class="button light" href="#pachete">Intru în Basic ${icon('arrow')}</a><a class="button gold" href="#pachete">Vreau VIP ${icon('arrow')}</a></div><small>Începem pe 1 septembrie · Onboarding pe 31 august · Maximum 12 locuri VIP</small></div></section>
</main>
<footer><div><a class="logo" href="#top"><b>B↗</b><span>BACK TO <strong>SALES</strong></span></a><p>Un challenge practic pentru un proces comercial clar, etic și măsurabil.</p></div><div><b>Program</b><a href="#proces">Procesul</a><a href="#program">Cele 30 de zile</a><a href="#pachete">Basic & VIP</a></div><div><b>Legal</b><a href="/termeni/">Termeni și condiții</a><a href="/confidentialitate/">Confidențialitate / GDPR</a><a href="/cookies/">Politica de cookies</a><a href="/retragere/">Retrageți-vă din contract aici</a></div><div><b>Contact</b><a href="tel:+40746266529">0746 266 529</a><a href="mailto:claudia_cioceanu@yahoo.com">claudia_cioceanu@yahoo.com</a><a href="https://anpc.ro/sal/" target="_blank" rel="noopener">Soluționare alternativă ANPC</a></div><small>© 2026 Desire to Develop SRL · CUI 37611127 · J15/676/2017</small></footer>
<a class="mobile-cta" href="#pachete">Vezi pachetele · de la 179 lei ${icon('arrow')}</a></div>`

const bar=document.querySelector('.scroll-progress span');addEventListener('scroll',()=>{const m=document.documentElement.scrollHeight-innerHeight;bar.style.width=`${m?scrollY/m*100:0}%`},{passive:true})
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x))
const earlyBirdEnds=new Date('2026-08-23T23:59:59+03:00')
if(new Date()>earlyBirdEnds)document.querySelectorAll('.price-card').forEach(card=>{const payment=card.querySelector('.payment'),price=payment.dataset.plan==='basic'?'237':'537';card.querySelector('.offer-label').textContent='PREȚ STANDARD';card.querySelector('.price-value').textContent=price;card.querySelector('.price-note').textContent='Înscrieri până pe 30 august, ora 23:59';card.querySelector('.button-price').textContent=price;payment.href=payment.dataset.standard})
