import './style.css'

const icon = name => {
  const paths = {arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',spark:'<path d="m12 3 1.6 4.4L18 9l-4.4 1.6L12 15l-1.6-4.4L6 9l4.4-1.6L12 3Z"/>',chart:'<path d="M4 19V9m6 10V5m6 14v-7m4 7H2"/>',message:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v8Z"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="m15 9 6-6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'}
  return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]}</svg>`
}
const checks = items => `<ul class="check-list">${items.map(x=>`<li>${icon('check')}<span>${x}</span></li>`).join('')}</ul>`
const problems=['Activitatea merge, dar vânzările depind încă prea mult de tine, de recomandări sau de perioadele bune.','Te ocupi de clienți, livrare, promovare și administrativ, iar vânzarea ajunge mereu la finalul listei.','Ai conversații și cereri de ofertă, dar nu ai un mod consecvent de a le duce mai departe.','Eviți follow-up-ul sau discuția despre preț pentru că nu vrei să pari insistent.','Nu urmărești suficient de clar de unde vin oportunitățile și unde se pierd.']
const steps=[['Creezi oportunități','Alegi canalele prin care poți ajunge constant la oamenii potriviți, nu doar când scad încasările.'],['Înțelegi nevoia','Pui întrebări, afli contextul și vezi dacă există o potrivire reală înainte să prezinți soluția.'],['Prezinți oferta','Legi clar problema de soluție și explici valoarea, modul de lucru, durata și prețul.'],['Faci follow-up','Stabilești când și cum revii, ca să nu pierzi conversații bune și să nu te simți insistent.'],['Urmărești decizia','Clarifici ce îl oprește pe client și închei conversația cu un răspuns, nu cu o așteptare fără termen.']]
const weeks=[['Baza de la care pornești',['Oferta pe care merită să o pui în prim-plan','Locurile în care procesul tău se oprește acum']],['Oportunități și conversații',['Contexte potrivite pentru a ajunge la oameni','Un ritm compatibil cu programul și stilul tău']],['Oferta și decizia',['O prezentare mai clară a valorii și prețului','Mai multă siguranță când inviți omul să decidă']],['Follow-up și ce păstrezi',['Un mod firesc de a reveni la oamenii interesați','Concluzii bazate pe răspunsuri, nu pe presupuneri']]]
const faqs=[['Nu am o audiență mare. Are sens?','Da, dacă ai acces la oameni prin relații, comunități, recomandări, parteneriate sau conversații directe. Nu lucrăm doar cu postări.'],['Programul este doar pentru servicii?','Nu. Principiile se adaptează serviciilor, produselor, afacerilor locale și businessurilor din domenii diferite.'],['Cât timp îmi ia zilnic?','În medie, 20–40 de minute pentru misiune și acțiunea de vânzare. Unele zile pot cere mai mult, în funcție de canal și de business.'],['Dacă nu pot participa live?','Participarea este recomandată. Înregistrările rămân disponibile timp de 60 de zile.'],['Primesc scripturi?','Da. Primești modele pentru conversații, ofertă și follow-up, pe care le adaptezi limbajului și contextului tău.'],['Care este diferența dintre Basic și VIP?','Basic include procesul complet. VIP adaugă audit, feedback direct, patru sesiuni suplimentare și hot seats. VIP este limitat la 12 locuri.'],['Îmi garantezi că voi vinde?','Nu. Rezultatul depinde de ofertă, piață, preț și felul în care aplici. Primești cadrul, practica și feedbackul care te ajută să creezi oportunități și să îmbunătățești procesul.'],['Primesc factură?','Da. Factura este emisă pe baza datelor completate după plată.'],['Ce se întâmplă după plată?','Primești confirmarea, completezi formularul de înscriere, apoi primești accesul în comunitatea Back to Sales.'],['Care este politica de retragere?','Drepturile tale sunt cele prevăzute de legislația aplicabilă contractelor la distanță. Consultă Termenii și condițiile înainte de plată.']]

document.querySelector('#app').innerHTML=`
<div class="page"><div class="scroll-progress"><span></span></div>
<header class="site-header"><a class="logo" href="#top"><b>B↗</b><span>BACK TO <strong>SALES</strong></span></a><nav><a href="#proces">Procesul</a><a href="#program">Programul</a><a href="#pachete">Pachete</a></nav><a class="button small" href="#pachete">Vreau să intru ${icon('arrow')}</a></header>
<main id="top">
<section class="hero shell"><div class="hero-copy reveal"><div class="kicker">— Challenge practic de vânzări • 1–30 septembrie</div><h1>Ajută-ți clientul să <em>cumpere</em> de la tine.</h1><p class="lead">În 30 de zile îți clarifici traseul comercial și faci <strong>100 de acțiuni concrete</strong> prin care clientul potrivit te poate vedea, poate intra în conversație, poate înțelege oferta și poate lua o decizie.</p><p class="no-pressure">Fără mesaje trimise în masă. Fără presiune.<br>Fără promisiuni de venit care nu depind numai de tine.</p><div class="hero-actions"><a class="button gold" href="#pachete">Vreau să intru în Back to Sales ${icon('arrow')}</a><span><b>Early Bird</b><br>Doar până pe 23 august</span></div></div>
<div class="hero-visual reveal"><i class="orbit"></i><i class="sphere"></i><div class="dashboard"><div class="dash-top"><span>PROGRES COMERCIAL</span><span>● LIVE</span></div><strong>100</strong><p>acțiuni măsurabile</p><div class="bars">${'<i></i>'.repeat(7)}</div><div class="stats"><span><b>30</b>zile</span><span><b>5</b>etape</span><span><b>1</b>proces</span></div></div><div class="float one">${icon('target')}<span><b>Claritate</b> înainte de acțiune</span></div><div class="float two">${icon('message')}<span><b>Conversații</b> care avansează</span></div></div></section>
<div class="trust">${[["clock","30 de zile","de acțiune ghidată"],["chart","100 de acțiuni","comerciale urmărite"],["message","Scripturi și exemple","adaptabile"],["users","Feedback","și comunitate"]].map(x=>`<div>${icon(x[0])}<span><b>${x[1]}</b>${x[2]}</span></div>`).join('')}</div>

<section class="section soft"><div class="shell intro reveal"><small>01 / REALITATEA</small><h2>Muncești mult în business. Dar câte acțiuni pot duce la o <em>vânzare?</em></h2><p>Poate ai un produs bun, experiență și clienți mulțumiți. Și totuși, vânzările sunt inegale. Într-o lună apar recomandări. În alta, scad încasările și îți dai seama că nu ai un proces pe care să te bazezi.</p></div><div class="shell problem-grid reveal">${problems.map((x,i)=>`<article><b>0${i+1}</b><p>${x}</p></article>`).join('')}</div><div class="shell insight reveal"><b>Problema nu este că nu muncești suficient.</b><p>De multe ori muncești enorm, dar acțiunile comerciale sunt prea rare, neclare sau se opresc înainte de ofertă și decizie.</p><a href="#pachete">Vreau un ritm clar ${icon('arrow')}</a></div></section>

<section class="section dark"><div class="shell two-col reveal"><div><small>02 / SCHIMBAREA DE PERSPECTIVĂ</small><h2>Vânzarea nu începe când spui <em>prețul.</em></h2></div><div><p>Clientul nu cumpără doar pentru că produsul tău este bun. Mai întâi trebuie să afle că exiști. Să se recunoască în problemă. Să intre într-o conversație. Să înțeleagă soluția, prețul și implementarea. Apoi să poată lua o decizie.</p><p>Dacă nu ai vizibilitate, ai nevoie de distribuție. Dacă oamenii nu se recunosc în mesaj, ai nevoie de limbajul lor. Dacă pornești conversații, dar nu faci oferta, încă o postare nu rezolvă evitarea. Dacă există interes și nu revii, pierzi leaduri deja câștigate.</p></div></div><div class="shell principle reveal">${icon('spark')}<p>Nu ai nevoie să împingi oamenii să cumpere. Ai nevoie să construiești traseul prin care clientul potrivit își identifică nevoia, înțelege dacă oferta îl ajută și poate alege informat.</p></div></section>

<section class="section" id="proces"><div class="shell reveal"><small>03 / MECANISMUL BACK TO SALES</small><div class="title-row"><h2>Cele 5 categorii care construiesc <em>vânzarea.</em></h2><p>100 de acțiuni distribuite inteligent — ca să vezi ce produce interes, conversații, oferte și decizii.</p></div><div class="steps">${steps.map((x,i)=>`<article><b>0${i+1}</b><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>

<section class="section soft"><div class="shell volume reveal"><div class="hundred"><strong>100</strong><span>ACȚIUNI<br>NU PRESUPUNERI</span></div><div><small>04 / DE CE VOLUM?</small><h2>Șase încercări nu sunt suficiente ca să spui <em>„nu funcționează”.</em></h2><p>Cu volum și măsurare apar tipare: ce mesaj deschide conversația, ce client răspunde, unde oamenii se opresc, ce obiecție se repetă și ce canal aduce leaduri potrivite.</p><blockquote>Nu poți controla cine cumpără. Dar poți controla câte ocazii reale creezi și cât de bine înveți din răspunsul pieței.</blockquote></div></div></section>

<section class="section"><div class="shell reveal"><small>05 / REZULTATUL</small><div class="title-row"><h2>La final ai un <em>proces testat de tine.</em></h2><p>Un sistem comercial mai clar, construit pe acțiuni și pe date din piața ta.</p></div><div class="outcomes">${checks(['O singură ofertă prioritară pentru septembrie.','O formulare mai clară a clientului și rezultatului.','Harta traseului de la primul contact la decizie.','Tracker cu 100 de acțiuni și răspunsuri.','Mai multe conversații pornite intenționat.','Un mod simplu de a prezenta oferta și prețul.'])}${checks(['Scripturi adaptabile, nu replici robotice.','Un sistem de follow-up fără presiune.','Lista obiecțiilor reale din piața ta.','Date care arată ce trebuie ajustat.','Un plan comercial pentru următoarele 30 de zile.'])}</div><div class="honesty"><b>O promisiune onestă</b><p>Nu promit un anumit număr de clienți sau o sumă de venit. Rezultatul depinde de ofertă, preț, piață și implementare. Programul îți oferă cadrul, acțiunile, feedbackul și datele necesare.</p></div></div></section>

<section class="section dark" id="program"><div class="shell reveal"><small>06 / CELE 30 DE ZILE</small><div class="title-row"><h2>Patru săptămâni. Un traseu comercial <em>complet.</em></h2><p>De la claritate la conversație, de la ofertă la decizie și optimizare.</p></div><div class="weeks">${weeks.map((x,i)=>`<article><div><b>0${i+1}</b><small>SĂPTĂMÂNA ${i+1}</small></div><h3>${x[0]}</h3>${checks(x[1])}</article>`).join('')}</div><div class="delivery">${[["clock","20–40 min / zi","Misiuni clare"],["chart","Tracker inclus","Acțiune și răspuns"],["users","Întâlniri săptămânale","Implementare"],["message","Grup + resurse","Scripturi și fișe"]].map(x=>`<div>${icon(x[0])}<span><b>${x[1]}</b><small>${x[2]}</small></span></div>`).join('')}</div></div></section>

<section class="section pricing" id="pachete"><div class="shell reveal"><small>07 / ALEGE VARIANTA</small><div class="title-row"><h2>Proces complet sau proces + <em>feedback personalizat.</em></h2><p>Basic nu este incomplet. VIP înseamnă mai multă personalizare și acces direct.</p></div><div class="price-grid">
<article class="price-card"><div class="plan"><b>BASIC</b><small>PENTRU STRUCTURĂ ȘI RITM</small></div><p>Pentru tine dacă ai nevoie de structură, misiuni și un ritm care să te scoată din amânare.</p>${checks(['Programul complet de 30 de zile','Misiuni zilnice + trackerul celor 100 de acțiuni','Warm-up înainte de start','4 întâlniri + sesiunea finală','Scripturi, exemple și fișa traseului','Grup comun și feedback colectiv','Materiale și înregistrări 60 de zile'])}<div class="price-block"><small class="offer-label">EARLY-BIRD</small><div><strong class="price-value">179</strong> LEI</div><p class="price-note">Doar până pe 23 august, ora 23:59</p></div><a class="button payment" data-plan="basic" data-standard="https://buy.stripe.com/aFaaEX7lT0sZ4bq8go5J60a" href="https://buy.stripe.com/eVqeVdeOl6Rn9vK8go5J608">Aleg Basic — <span class="button-price">179</span> lei ${icon('arrow')}</a></article>
<article class="price-card featured"><i>MAXIMUM 12 LOCURI</i><div class="plan"><b>VIP</b><small>PENTRU FEEDBACK DIRECT</small></div><p>Pentru tine dacă ai o ofertă mai complexă sau vrei feedback direct pe situația ta.</p>${checks(['Tot ce este inclus în Basic','Auditul ofertei și traseului clientului','4 sesiuni VIP suplimentare, în grup restrâns','Feedback pe pitch și comunicarea prețului','Feedback pe mesaje și follow-up','Analiza cifrelor și blocajelor','Grup VIP restrâns + prioritate'])}<div class="price-block"><small class="offer-label">EARLY-BIRD</small><div><strong class="price-value">437</strong> LEI</div><p class="price-note">Până pe 23 august, ora 23:59, sau în limita celor 12 locuri disponibile</p></div><a class="button gold payment" data-plan="vip" data-standard="https://buy.stripe.com/dRmeVdeOlcbH23i9ks5J60b" href="https://buy.stripe.com/28EbJ1ay58ZvfU82W45J609">Aleg VIP — <span class="button-price">437</span> lei ${icon('arrow')}</a></article></div><div class="choice" id="contact"><div><b>Nu știi ce să alegi?</b><p>Spune-mi ce vinzi și unde te blochezi. Îți recomand sincer varianta potrivită, nu cea mai scumpă.</p></div><a class="button outline contact" href="https://wa.me/40746266529?text=Bun%C4%83%2C%20Claudia!%20Vreau%20o%20recomandare%20pentru%20pachetul%20Back%20to%20Sales.">Scrie-mi pe WhatsApp ${icon('arrow')}</a></div></div></section>

<section class="section soft"><div class="shell fit reveal"><article><small>ESTE PENTRU TINE DACĂ</small><h2>Ai ceva valoros de pus în piață.</h2>${checks(['Ești freelancer, prestator, coach, terapeut, consultant sau trainer.','Ești creator, producător sau ai un business local.','Lucrezi în turism, educație, sănătate, construcții, retail sau servicii.','Ai experiență, dar nu ai un proces comercial repetabil.','Nu ai audiență mare, dar poți intra în conversații.'])}</article><article class="not-fit"><small>NU ESTE PENTRU TINE DACĂ</small><h2>Cauți o scurtătură fără acțiune.</h2>${checks(['Vrei o formulă prin care oamenii spun da indiferent de ofertă.','Vrei doar să citești, fără să faci acțiunile.','Aștepți venit sau clienți garantați.','Nu ai nicio idee ce vrei să vinzi.','Nu poți aloca 20–40 de minute pe zi.'])}</article></div></section>

<section class="section"><div class="shell about reveal"><div class="portrait"><img src="/claudia-cioceanu.jpeg" alt="Claudia Cioceanu, Business & Performance Coach" width="1008" height="1012"><span><b>CLAUDIA CIOCEANU</b><small>Business & Performance Coach</small></span><i>12 ani<small>experiență</small></i></div><div><small>08 / DESPRE CLAUDIA</small><h2>Nu te învăț o tehnică pe care am citit-o <em>ieri.</em></h2><p class="lead">Lucrez la intersecția dintre business, vânzări și comportamentul omului.</p><p>Sunt Claudia Cioceanu, Business & Performance Coach. Am 12 ani de experiență în corporație, în vânzări și coordonarea echipelor, și o bază de economist cu pregătire în management.</p><p>Lucrez cu antreprenori pe claritatea ofertei, poziționare, preț, acțiune, performanță și blocajele care îi fac să se țină mici.</p><p>Metoda mea pornește de la diagnostic: îl ajuți pe om să-și identifice nevoia, înțelegi contextul, prezinți soluția relevantă și îi lași libertatea unei decizii informate.</p><div class="credentials"><span>12 ani corporație</span><span>Vânzări + coordonare</span><span>Business & Performance Coach</span></div></div></div></section>

<section class="section stories"><div class="shell reveal"><small>09 / SITUAȚII REALE</small><div class="title-row"><h2>Problema nu este mereu cea spusă <em>prima dată.</em></h2><p>Cazuri anonimizate care arată unde se poate rupe procesul comercial.</p></div><div class="story-grid">${[['„Am nevoie de mai multe încasări.”','Antreprenorul era copleșit de operațional, nu făcuse oferte noi și nu revenise la cei interesați. Îi lipsea un loc clar pentru vânzare în fiecare zi.'],['„Nu știu dacă va funcționa.”','Fusese dezamăgit de soluții generale. Avea nevoie de un proces adaptat contextului, nu de încă un „fă marketing”.'],['„Oamenii nu cumpără.”','Leadurile existau, dar nu erau urmărite. Oferta varia, cifrele lipseau, iar conversațiile nu aveau pas următor.'],['„Nu vreau să deranjez.”','Oferă multă valoare, dar evită oferta. A vinde etic înseamnă claritate fără să forțezi.']].map(x=>`<article><i>“</i><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>

<section class="section promise"><div class="shell two-col reveal"><div><small>10 / CE NU PROMIT</small><h2>Fără magie.<br>Fără manipulare.<br><em>Cu proces.</em></h2></div><div>${checks(['Nu îți promit că fiecare acțiune produce o vânzare.','Nu îți promit o sumă sau un număr de clienți.','Nu îți promit că un script înlocuiește o ofertă slabă.','Nu te învăț să inventezi urgență sau să împingi oamenii.'])}<p class="promise-end">Îți ofer un proces în care <b>faci, măsori, înțelegi și ajustezi.</b></p></div></div></section>

<section class="section"><div class="shell faq reveal"><small>11 / ÎNTREBĂRI FRECVENTE</small><h2>Poate te întrebi...</h2>${faqs.map((x,i)=>`<details ${i===0?'open':''}><summary>${x[0]}<i></i></summary><p>${x[1]}</p></details>`).join('')}</div></section>

<section class="final"><div class="shell reveal"><small>ÎNSCRIERILE SE ÎNCHID PE 30 AUGUST · 23:59</small><h2>În septembrie poți spera că vânzările apar.<br><em>Sau poți construi acțiunile care le fac posibile.</em></h2><p>Nu trebuie să devii mai agresiv sau să postezi fără oprire. Ai nevoie să alegi acțiunile care pot produce un răspuns și să afli ce funcționează.</p><div><a class="button light" href="#pachete">Intru în Basic ${icon('arrow')}</a><a class="button gold" href="#pachete">Vreau VIP ${icon('arrow')}</a></div><small>Începem pe 1 septembrie · Primești accesul în comunitatea Back to Sales după înscriere · Maximum 12 locuri VIP</small></div></section>
</main>
<footer><div><a class="logo" href="#top"><b>B↗</b><span>BACK TO <strong>SALES</strong></span></a><p>Un challenge practic pentru un proces comercial clar, etic și măsurabil.</p></div><div><b>Program</b><a href="#proces">Procesul</a><a href="#program">Cele 30 de zile</a><a href="#pachete">Basic & VIP</a></div><div><b>Legal</b><a href="/termeni/">Termeni și condiții</a><a href="/confidentialitate/">Confidențialitate / GDPR</a><a href="/cookies/">Politica de cookies</a><a href="/retragere/">Retrageți-vă din contract aici</a></div><div><b>Contact</b><a href="tel:+40746266529">0746 266 529</a><a href="mailto:claudia_cioceanu@yahoo.com">claudia_cioceanu@yahoo.com</a><a href="https://anpc.ro/sal/" target="_blank" rel="noopener">Soluționare alternativă ANPC</a></div><small>© 2026 Desire to Develop SRL · CUI 37611127 · J15/676/2017</small></footer>
<a class="mobile-cta" href="#pachete">Vezi pachetele ${icon('arrow')}</a></div>`

// Copy revizuit: mai direct, mai firesc și mai ușor de parcurs.
const setCopy=(selector,html)=>{const element=document.querySelector(selector);if(element)element.innerHTML=html}
setCopy('.hero h1','Afacerea ta a crescut. Vânzările au rămas tot pe <em>umerii tăi.</em>')
setCopy('.hero-copy .lead','Back to Sales este un program practic de 30 de zile pentru oamenii care au deja clienți și experiență, dar încă vând printre toate celelalte lucruri pe care le au de făcut — fie că lucrează singuri, fie că au o echipă.')
setCopy('.hero-copy .no-pressure','Este pentru antreprenori, terapeuți, coachi, psihologi, consultanți și alți profesioniști care vor o bază de vânzări mai sănătoasă, chiar dacă vânzarea nu este partea lor preferată.')
setCopy('.hero-visual',`<div class="hero-photo-card"><img src="/claudia-hero.jpeg" alt="Claudia Cioceanu, ghidul challenge-ului Back to Sales" width="1086" height="1448"><div class="hero-guide"><b>Challenge ghidat de Claudia Cioceanu</b><span>Business & Performance Coach</span></div></div><div class="sales-map"><small>HARTA CHALLENGE-ULUI</small><ol><li><i>01</i><span>Oportunități</span></li><li><i>02</i><span>Nevoie</span></li><li><i>03</i><span>Ofertă</span></li><li><i>04</i><span>Follow-up</span></li><li><i>05</i><span>Decizie</span></li></ol></div>`)

setCopy('.intro h2','Nu ești la început în ceea ce faci. Dar vânzarea poate avea încă <em>goluri.</em>')
setCopy('.intro p','Poate ai ani de experiență, clienți mulțumiți și o ofertă bună. Numai că între lucrul cu clienții, sesiuni sau livrare, promovare și administrativ, vânzarea se întâmplă când mai rămâne timp ori când încasările îți cer să te ocupi urgent de ea.')
document.querySelector('.intro p')?.insertAdjacentHTML('afterend','<p>Poate ai deja vizibilitate, cereri de ofertă și conversații cu potențiali clienți, dar prea puține ajung la follow-up și la o decizie clară.</p>')
document.querySelector('.problem-grid')?.insertAdjacentHTML('beforebegin','<h3 class="problem-title shell">Este pentru tine dacă...</h3>')
setCopy('.insight b','Nu ai nevoie să o iei de la zero. Ai nevoie să pui în ordine ceea ce faci deja.')
setCopy('.insight p','Să știi cum creezi oportunități, cum duci o conversație spre ofertă, când revii și ce urmărești ca să nu depinzi doar de inspirație, recomandări sau perioade bune.')

const perspective=document.querySelector('.dark .two-col')
if(perspective){const paragraphs=perspective.querySelectorAll('p');paragraphs[0].textContent='Poți avea un produs bun, reputație și clienți mulțumiți, dar toate acestea nu înlocuiesc un proces de vânzare. Oportunitățile trebuie create, urmărite și duse spre o decizie.';paragraphs[1].textContent='În Back to Sales vezi unde se oprește acum procesul tău: la atragerea oamenilor potriviți, în conversație, la ofertă, la follow-up sau înainte de decizie. Apoi lucrezi exact la acel punct.'}
setCopy('.principle p','Nu trebuie să împingi pe nimeni să cumpere. Îl ajuți pe clientul potrivit să înțeleagă dacă oferta ta i se potrivește și să decidă în cunoștință de cauză.')

setCopy('#proces small','03 / CUM SE LEAGĂ VÂNZAREA')
setCopy('#proces .title-row h2','Cum ajunge un om de la primul contact la <em>o decizie.</em>')
setCopy('#proces .title-row p','Urmărești cinci momente simple și vezi unde se opresc acum conversațiile tale.')
const volumeSection=document.querySelector('.volume')?.closest('section')
if(volumeSection)volumeSection.remove()

const outcomeSection=document.querySelector('.outcomes')?.closest('section')
if(outcomeSection){setCopy('.outcomes',checks(['Alegi o ofertă prioritară și clarifici pentru cine este.','Creezi mai multe contexte reale de conversație cu potențiali clienți.','Prezinți mai simplu valoarea, oferta și prețul.'])+checks(['Faci follow-up fără presiune și fără mesaje copiate în masă.','Observi ce mesaje, canale și acțiuni produc răspuns.','Pleci cu un proces de vânzare mai clar pentru următoarele 30 de zile.']));const title=outcomeSection.querySelector('.title-row h2');if(title)title.innerHTML='Ce se schimbă în cele <em>30 de zile.</em>';const intro=outcomeSection.querySelector('.title-row p');if(intro)intro.textContent='Nu rămâi doar cu informații. Lucrezi pe oferta și situațiile tale, apoi urmărești ce răspunde piața.';const honesty=outcomeSection.querySelector('.honesty');if(honesty)honesty.innerHTML='<b>Ce urmărim, de fapt</b><p>Să nu mai vinzi doar când „se întâmplă”, ci să știi ce acțiuni creează oportunități reale în businessul tău. Nu îți promit un număr de clienți sau o sumă de venit.</p>'}

setCopy('#program .title-row h2','Patru săptămâni în care îți construiești o bază de vânzări <em>mai sănătoasă.</em>')
setCopy('#program .title-row p','Vezi ce are nevoie de atenție în cazul tău și lucrezi aplicat, fără o rețetă universală.')
const deliveryLabels=[['20–40 min / zi','Misiuni scurte'],['Tracker simplu','Acțiuni și răspunsuri'],['Întâlniri live','Lucrăm aplicat'],['Grup + materiale','Întrebări și exemple']]
document.querySelectorAll('.delivery > div').forEach((item,index)=>{const label=deliveryLabels[index];if(!label)return;item.querySelector('b').textContent=label[0];item.querySelector('small').textContent=label[1]})

setCopy('.pricing .title-row h2','Alege nivelul de sprijin de care <em>ai nevoie.</em>')
setCopy('.pricing .title-row p','Ambele pachete includ procesul complet. Diferența este nivelul de feedback personalizat.')
const priceCards=document.querySelectorAll('.price-card')
if(priceCards[0]){priceCards[0].querySelector(':scope > p').textContent='Alegi Basic dacă vrei structura completă și poți aplica singur după ghidajul și feedbackul din grup.';priceCards[0].querySelector('.check-list').innerHTML=checks(['Programul complet de 30 de zile','Misiuni zilnice și tracker pentru acțiunile tale','4 întâlniri de grup și sesiunea finală','Modele pentru conversații, ofertă și follow-up','Grup comun și feedback colectiv','Materiale și înregistrări disponibile 60 de zile']).replace(/^<ul class="check-list">|<\/ul>$/g,'')}
if(priceCards[1]){priceCards[1].querySelector(':scope > p').textContent='Alegi VIP dacă vrei să lucrăm direct pe oferta, mesajele și blocajele tale, în patru sesiuni restrânse suplimentare.';priceCards[1].querySelector('.check-list').innerHTML=checks(['Tot ce este inclus în Basic','4 sesiuni VIP suplimentare, în grup restrâns','Auditul ofertei și al parcursului clientului','Feedback pe pitch, preț, mesaje și follow-up','Hot seats pe situații reale din business','În total, 8 întâlniri pe parcursul programului']).replace(/^<ul class="check-list">|<\/ul>$/g,'')}
setCopy('.hero-actions > span','<b>Early Bird</b><br>Doar până pe 23 august')
priceCards.forEach(card=>{const current=card.querySelector('.price-value');if(!current)return;const standard=card.classList.contains('featured')?'537':'237';current.insertAdjacentHTML('beforebegin',`<s class="standard-price">${standard} lei</s>`)})
priceCards.forEach(card=>{const note=card.querySelector('.price-note');if(!note)return;note.textContent=card.classList.contains('featured')?'Până pe 23 august, ora 23:59, sau în limita celor 12 locuri disponibile':'Doar până pe 23 august, ora 23:59'})
document.querySelector('.secure')?.remove()
priceCards.forEach(card=>card.querySelector(':scope > .button + small')?.remove())
const choice=document.querySelector('.choice')
if(choice){choice.querySelector('b').textContent='Ai o întrebare înainte să te înscrii?';choice.querySelector('p').textContent='Scrie-mi pe WhatsApp și îți răspund cu drag.'}

const fitCards=document.querySelectorAll('.fit article')
if(fitCards[0]){fitCards[0].querySelector('h2').innerHTML='Ai deja ceva valoros de oferit. Vrei o bază de vânzări <em>mai sănătoasă.</em>';fitCards[0].querySelector('.check-list').innerHTML=checks(['Ești soloprenor, terapeut, coach, psiholog, consultant, freelancer sau antreprenor.','Ai deja o ofertă, clienți sau experiență în piață.','Faci singur multe dintre lucrurile din activitatea ta, inclusiv vânzarea.','Depinzi prea mult de recomandări sau de perioadele în care oamenii vin singuri spre tine.','Vrei să vinzi mai consecvent, fără să devii agresiv și fără să joci un rol.']).replace(/^<ul class="check-list">|<\/ul>$/g,'')}
if(fitCards[1]){fitCards[1].querySelector('h2').textContent='Cauți o soluție fără implicare sau pornești complet de la zero.';fitCards[1].querySelector('.check-list').innerHTML=checks(['Nu ai încă o ofertă pe care să o poți vinde.','Vrei doar informații, fără să aplici în business.','Aștepți venituri sau clienți garantați.','Cauți replici prin care oamenii să spună da indiferent de potrivire.','Nu poți aloca 20–40 de minute pe zi.']).replace(/^<ul class="check-list">|<\/ul>$/g,'')}

const about=document.querySelector('.about')
if(about){setCopy('.about > div:last-child > small','08 / CINE TE GHIDEAZĂ');setCopy('.about h2','Experiență practică în business, vânzări și <em>lucrul cu oamenii.</em>');setCopy('.about .lead','Sunt Claudia Cioceanu, Business & Performance Coach.');const paragraphs=about.querySelectorAll(':scope > div:last-child > p');if(paragraphs[1])paragraphs[1].textContent='Am 19 ani de experiență profesională, dintre care 12 ani în corporație, în vânzări și coordonarea echipelor, cu o bază de economist și pregătire în management.';if(paragraphs[2])paragraphs[2].textContent='Lucrez cu antreprenori pe claritatea ofertei, poziționare, preț, acțiune, performanță și blocajele care îi țin pe loc.';if(paragraphs[3])paragraphs[3].textContent='Începem cu întrebări clare: ce vinzi, cui, unde se opresc conversațiile și ce ai de testat. Apoi lucrăm pe situațiile tale, nu pe exemple fără legătură cu businessul tău.';about.querySelector('.portrait i')?.remove();setCopy('.credentials','<span>Vânzări + coordonare</span><span>Business & Performance Coach</span>')}

setCopy('.promise h2','Nu îți ofer clienți.<br>Îți ofer un <em>cadru de lucru aplicabil.</em>')
setCopy('.promise-end','Îți ofer contextul în care să îți pui acțiunile în ordine și să le faci — chiar dacă, de multe ori, <b>știi deja ce ai de făcut.</b>')
const faq=document.querySelector('.faq')
if(faq){const firstDetails=faq.querySelector('details');firstDetails?.insertAdjacentHTML('beforebegin','<details open><summary>Este un program pentru afaceri la început?<i></i></summary><p>Nu este un curs despre cum să pornești o afacere. Este potrivit mai ales dacă ai deja o ofertă, experiență și acces la potențiali clienți, dar vânzarea nu are încă o structură sănătoasă și consecventă.</p></details>');if(firstDetails)firstDetails.removeAttribute('open')}
document.querySelectorAll('section small').forEach(label=>{if(/^\d{2}\s*\//.test(label.textContent.trim()))label.remove()})
setCopy('.final h2','Poți continua să faci vânzări printre toate celelalte lucruri.<br><em>Sau poți construi un proces pe care să te bazezi.</em>')
setCopy('.final p','Nu trebuie să devii mai agresiv și nici să te transformi într-un om căruia îi place să vândă. Ai nevoie de o bază sănătoasă și de acțiuni pe care le poți repeta consecvent.')
setCopy('.final>div>small:last-child','Începem pe 1 septembrie · Primești accesul în comunitatea Back to Sales după înscriere · Maximum 12 locuri VIP')

const bar=document.querySelector('.scroll-progress span');addEventListener('scroll',()=>{const m=document.documentElement.scrollHeight-innerHeight;bar.style.width=`${m?scrollY/m*100:0}%`},{passive:true})
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x))
const earlyBirdEnds=new Date('2026-08-23T23:59:59+03:00')
if(new Date()>earlyBirdEnds){setCopy('.hero-actions > span','<b>Înscrierile sunt deschise</b><br>Până pe 30 august');document.querySelectorAll('.price-card').forEach(card=>{const payment=card.querySelector('.payment'),price=payment.dataset.plan==='basic'?'237':'537';card.querySelector('.standard-price')?.remove();card.querySelector('.offer-label').textContent='PREȚ STANDARD';card.querySelector('.price-value').textContent=price;card.querySelector('.price-note').textContent='Înscrieri până pe 30 august, ora 23:59';card.querySelector('.button-price').textContent=price;payment.href=payment.dataset.standard})}
